export const ALL_TRACK_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_TRACK_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_TRACK_FAIL = "ALL_PRODUCT_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";